export default {
    getHomeData:()=>{
        return{
            coda:200,
            data:{
                tableData:[
                    {
                    name:'oppo',
                    totayBuy:'500',
                    monthBuy:'500',
                    totalBuy:'1000',
                    },
                    {
                    name:'一加',
                    totayBuy:'500',
                    monthBuy:'500',
                    totalBuy:'1000',
                    },
                    {
                    name:'apple',
                    totayBuy:'500',
                    monthBuy:'500',
                    totalBuy:'1000',
                    },
                    {
                    name:'华为',
                    totayBuy:'500',
                    monthBuy:'500',
                    totalBuy:'1000',
                    },
        
                ]
            },
        }
    }
};